###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mariadb:
      image: mariadb:10.1
      container_name: mariadb
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=beeriously
        - MYSQL_USER=growler
        - MYSQL_PASSWORD=password
      networks:
        - beeriously
      ports:
        - "62338:3306"
    beeriously-php-fpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      working_dir: /application
      container_name: beeriously-php-fpm
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      links:
        - mariadb
      networks:
        - beeriously
networks:
  beeriously:
    driver: "bridge"
